### ISSUE TITLE
error when running with docker

### ISSUE THREAD

**Issue by nlehuby** [hiposfer/o2g#131]
When I use the command line in the readme, I get the following error:
`docker run -it -p 3000:3000 hiposfer/o2g`

```
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from o2g.cli import main
  File "/usr/lib/python3.6/site-packages/o2g/cli.py", line 18, in <module>
    from o2g.osm.exporter import TransitDataExporter
  File "/usr/lib/python3.6/site-packages/o2g/osm/exporter.py", line 3, in <module>
    from o2g.osm.handlers import RelationHandler, NodeHandler, WayHandler
  File "/usr/lib/python3.6/site-packages/o2g/osm/handlers/__init__.py", line 1, in <module>
    from .relation_handler import RelationHandler
  File "/usr/lib/python3.6/site-packages/o2g/osm/handlers/relation_handler.py", line 1, in <module>
    import osmium as o
  File "/usr/lib/python3.6/site-packages/osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: Error loading shared library libboost_python36.so.1.67.0: No such file or directory (needed by /usr/lib/python3.6/site-packages/osmium/_osmium.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by mehdisadeghi** [comment]
Thanks for reporting. I'll take care of this. Apparently my recent docker builds are broken.

**Comment by mehdisadeghi** [comment]
It should work [now](https://github.com/hiposfer/o2g/commit/0b8e97a48637e330d566db3ef714f342fc314812). Make sure to delete the local image before retrying `docker rmi hiposfer/o2g`.

**Comment by mehdisadeghi** [comment]
The problem was that the base docker image has moved from python3.6 to 3.7 therefore some of the instructions in the dockerfile were failing. I used this image since it the smallest around and since it only offers a `latest` tag I can't choose 3.6-based image explicitely.
